version: '3.3'

services:
  sharee-website:
    image: sharee-website:dev
    command: npm run build
    environment:
      PORT: 3000
    volumes:
      - "./src/:/sharee-website/src/"
      - "./build/:/sharee-website/build/"
      - "./public/:/sharee-website/public/"
